/*
 * glasswally.yar — YARA rules for LLM distillation attack detection
 *
 * Generated from Glasswally Rust pattern definitions.
 * Auto-generated by: cargo xtask gen-yara
 *
 * Usage contexts:
 *   - Network inspection (Suricata, Zeek with YARA plugin)
 *   - Endpoint security (osquery, CrowdStrike custom IOAs)
 *   - SIEM enrichment (Elastic, Splunk TA)
 *   - Proxy/WAF inspection (nginx + YARA module)
 *
 * All rules scan HTTP request body content (JSON payload) captured at TLS
 * termination.  Rules are complementary — combine scores using the meta.weight
 * field to compute a composite risk score matching Glasswally's fusion engine.
 *
 * Version: 0.1.0
 * Maintainer: m0rs3c0d3
 */

// ── CoT Elicitation patterns ─────────────────────────────────────────────────
// Source: glasswally/src/workers/cot.rs

rule GW_COT_ELICITATION_STRONG
{
    meta:
        description  = "Strong chain-of-thought elicitation pattern — explicit reasoning request"
        worker       = "cot"
        weight       = 0.09
        score_base   = 0.70
        reference    = "T-DIST-001"
        severity     = "HIGH"

    strings:
        $s1 = "think step by step" nocase
        $s2 = "let's reason carefully" nocase
        $s3 = "reason through each step" nocase
        $s4 = "show your work step by step" nocase
        $s5 = "explain each step of your reasoning" nocase
        $s6 = "walk me through your reasoning" nocase
        $s7 = "provide a detailed chain of thought" nocase

    condition:
        any of them
}

rule GW_COT_ELICITATION_MODERATE
{
    meta:
        description  = "Moderate CoT elicitation — may be legitimate research or extraction"
        worker       = "cot"
        weight       = 0.09
        score_base   = 0.40
        reference    = "T-DIST-001"
        severity     = "MEDIUM"

    strings:
        $s1 = "first, let's" nocase
        $s2 = "step 1:" nocase
        $s3 = "think out loud" nocase
        $s4 = "explain your thinking" nocase
        $s5 = "show all steps" nocase
        $s6 = "break this down" nocase

    condition:
        2 of them
}

// ── Role preamble patterns ────────────────────────────────────────────────────
// Source: glasswally/src/workers/role_preamble.rs

rule GW_ROLE_EXTRACTION_STRONG
{
    meta:
        description  = "Role preamble optimised for capability extraction — 'never refuse' + 'always complete'"
        worker       = "role_preamble"
        weight       = 0.06
        score_base   = 0.65
        reference    = "T-DIST-001"
        severity     = "HIGH"

    strings:
        $never1 = "never refuse" nocase
        $never2 = "never say you cannot" nocase
        $never3 = "do not refuse" nocase
        $comp1  = "always provide complete" nocase
        $comp2  = "respond with maximum detail" nocase
        $comp3  = "do not add disclaimers" nocase
        $comp4  = "omit caveats" nocase
        $comp5  = "respond without restrictions" nocase

    condition:
        1 of ($never*) and 1 of ($comp*)
}

rule GW_ROLE_EXPERT_EXTRACTION
{
    meta:
        description  = "Expert persona role with data collection framing"
        worker       = "role_preamble"
        weight       = 0.06
        score_base   = 0.45
        reference    = "T-DIST-001"
        severity     = "MEDIUM"

    strings:
        $expert1 = "you are an expert" nocase
        $expert2 = "you are a world-class" nocase
        $expert3 = "you are a highly skilled" nocase
        $data1   = "your answers will be used to train" nocase
        $data2   = "your responses are being recorded" nocase
        $data3   = "generate high-quality training examples" nocase
        $data4   = "answer as if explaining to another ai" nocase

    condition:
        1 of ($expert*) or 1 of ($data*)
}

rule GW_TASK_CHAIN_PREAMBLE
{
    meta:
        description  = "Numbered task list in system prompt — systematic extraction task chain"
        worker       = "role_preamble"
        weight       = 0.06
        score_base   = 0.35
        reference    = "T-DIST-001"
        severity     = "MEDIUM"

    strings:
        $t1 = "task 1:" nocase
        $t2 = "step 1:" nocase
        $t3 = "question 1:" nocase

    condition:
        any of them
}

// ── Token budget probing ───────────────────────────────────────────────────────
// Source: glasswally/src/workers/token_budget.rs

rule GW_MAX_TOKENS_EXTREME
{
    meta:
        description  = "Requesting maximum possible token budget — greedy extraction"
        worker       = "token_budget"
        weight       = 0.03
        score_base   = 0.30
        reference    = "T-DIST-001"
        severity     = "LOW"

    strings:
        // Common max_tokens values seen in API payloads
        $m1 = "\"max_tokens\":128000" nocase wide ascii
        $m2 = "\"max_tokens\":200000" nocase wide ascii
        $m3 = "\"max_tokens\":32768"  nocase wide ascii
        $m4 = "\"max_tokens\":16384"  nocase wide ascii
        $m5 = "\"max_tokens\":8192"   nocase wide ascii
        $m6 = "max_tokens\": 128000"  nocase wide ascii
        $m7 = "max_tokens\": 32768"   nocase wide ascii

    condition:
        any of them
}

// ── Refusal probe patterns ────────────────────────────────────────────────────
// Source: glasswally/src/workers/refusal_probe.rs

rule GW_REFUSAL_PROBE_VIOLENCE
{
    meta:
        description  = "Violence-category refusal probe — testing model safety boundary"
        worker       = "refusal_probe"
        weight       = 0.02
        score_base   = 0.35
        reference    = "T-DIST-007"
        severity     = "MEDIUM"

    strings:
        $s1 = "how to kill" nocase
        $s2 = "how to attack" nocase
        $s3 = "instructions for violence" nocase
        $s4 = "how to make a weapon" nocase
        $s5 = "how to build a bomb" nocase

    condition:
        any of them
}

rule GW_REFUSAL_PROBE_CBRN
{
    meta:
        description  = "CBRN-category refusal probe — testing WMD knowledge boundary"
        worker       = "refusal_probe"
        weight       = 0.02
        score_base   = 0.50
        reference    = "T-DIST-007"
        severity     = "HIGH"

    strings:
        $s1 = "biological weapon" nocase
        $s2 = "chemical weapon" nocase
        $s3 = "nerve agent" nocase
        $s4 = "ricin synthesis" nocase
        $s5 = "bioweapon" nocase
        $s6 = "dirty bomb" nocase
        $s7 = "radiological weapon" nocase

    condition:
        any of them
}

rule GW_REFUSAL_PROBE_DRUGS
{
    meta:
        description  = "Drug synthesis refusal probe"
        worker       = "refusal_probe"
        weight       = 0.02
        score_base   = 0.40
        reference    = "T-DIST-007"
        severity     = "MEDIUM"

    strings:
        $s1 = "how to synthesize" nocase
        $s2 = "drug synthesis" nocase
        $s3 = "precursor chemicals" nocase
        $s4 = "cook meth" nocase
        $s5 = "manufacture cocaine" nocase

    condition:
        any of them
}

// ── Watermark / Canary probe detection ───────────────────────────────────────
// Source: glasswally/src/workers/watermark.rs

rule GW_ZERO_WIDTH_CHARS_IN_PROMPT
{
    meta:
        description  = "Zero-width Unicode characters in prompt — watermarked scraped content reproduced"
        worker       = "watermark"
        weight       = 0.04
        score_base   = 0.60
        reference    = "T-DIST-008"
        severity     = "HIGH"

    strings:
        // ZWJ U+200D (UTF-8: e2 80 8d) and ZWNJ U+200C (UTF-8: e2 80 8c)
        $zwj  = { e2 80 8d }
        $zwnj = { e2 80 8c }
        // BOM / ZERO WIDTH NO-BREAK SPACE U+FEFF
        $zwnbs = { ef bb bf }

    condition:
        any of them
}

rule GW_VERBATIM_REPRODUCTION_PROBE
{
    meta:
        description  = "Prompt requesting verbatim/complete reproduction — maximising training signal"
        worker       = "watermark"
        weight       = 0.04
        score_base   = 0.25
        reference    = "T-DIST-008"
        severity     = "LOW"

    strings:
        $s1 = "verbatim" nocase
        $s2 = "word for word" nocase
        $s3 = "reproduce exactly" nocase
        $s4 = "copy exactly" nocase
        $s5 = "do not summarise" nocase
        $s6 = "do not truncate" nocase
        $s7 = "full response" nocase
        $s8 = "complete response" nocase

    condition:
        2 of them
}

// ── gRPC / HTTP2 bulk extraction ─────────────────────────────────────────────
// Source: glasswally/src/workers/h2_grpc.rs

rule GW_GRPC_API_ACCESS
{
    meta:
        description  = "gRPC content-type in API request — high-throughput bulk extraction vector"
        worker       = "h2_grpc"
        weight       = 0.06
        score_base   = 0.35
        reference    = "T-DIST-010"
        severity     = "MEDIUM"

    strings:
        $ct1 = "content-type: application/grpc" nocase
        $ct2 = "content-type:application/grpc" nocase
        $hdr1 = "grpc-encoding:" nocase
        $hdr2 = "grpc-timeout:" nocase

    condition:
        any of them
}

// ── Composite high-risk rule (fusion) ─────────────────────────────────────────

rule GW_HIGH_RISK_COMPOSITE
{
    meta:
        description  = "Multiple Glasswally distillation signals present — high-confidence alert"
        worker       = "fusion"
        weight       = 1.0
        score_base   = 0.80
        reference    = "T-DIST-001,T-DIST-002,T-DIST-003"
        severity     = "CRITICAL"

    condition:
        (GW_COT_ELICITATION_STRONG or GW_COT_ELICITATION_MODERATE)
        and
        (GW_ROLE_EXTRACTION_STRONG or GW_ROLE_EXPERT_EXTRACTION)
        and
        (GW_MAX_TOKENS_EXTREME or GW_VERBATIM_REPRODUCTION_PROBE)
}
